name: propertymanagementsys
description: "A new Flutter project."

publish_to: 'none'  


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  kiwi: ^4.1.0
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  toastification: ^2.3.0
  image_picker: ^1.0.8
  json_annotation: ^4.8.1
  # Get is for context less location of cubit
  get: ^4.6.6
  repository:
    path: packages/repository
  syncfusion_flutter_datagrid: ^27.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  kiwi_generator: ^4.1.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
 
  uses-material-design: true

 